name: Docker Build and Push to GAR

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PROJECT_ID: invintory
  GAR_LOCATION: us-east1
  REPOSITORY: firecrawl-playwright-ts
  IMAGE: firecrawl-playwright
  REGION: us-east1
  SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for GAR
        run: |
          gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./apps/playwright-service-ts
          push: true
          tags: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  # deploy-cloud-run:
  #   name: Deploy API
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Google Auth
  #       id: auth
  #       uses: google-github-actions/auth@v2
  #       with:
  #         credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"
  #     - name: Set up Cloud SDK
  #       uses: google-github-actions/setup-gcloud@v2
  #     - name: Deploy to Cloud Run API
  #       run: |
  #         gcloud run deploy firecrawl-playwright \
  #           --project ${{ env.PROJECT_ID }} \
  #           --region ${{ env.REGION }} \
  #           --image ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }} \
  #           --update-env-vars GIT_SHA=${{ github.sha }}

  # send-slack-notification:
  #   name: Send Slack Notification
  #   runs-on: ubuntu-latest
  #   needs: [deploy-cloud-run]
  #   steps:
  #     - name: Send Slack webhook
  #       uses: slackapi/slack-github-action@v1
  #       with:
  #         payload: |
  #           {
  #             "text": "Deployment completed for ${{ github.repository }}",
  #             "mrkdwn": true,
  #             "attachments": [
  #               {
  #                 "color": "${{ job.status == 'success' && 'good' || 'danger' }}",
  #                 "fields": [
  #                   {
  #                     "title": "Status",
  #                     "value": "${{ job.status }}",
  #                     "short": true
  #                   },
  #                   {
  #                     "title": "Workflow Steps",
  #                     "value": "${{ toJson(steps) }}",
  #                     "short": false
  #                   }
  #                 ],
  #                 "footer_icon": "https://github.githubassets.com/favicon.ico"
  #               }
  #             ]
  #           }
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}
